version: '3.8'

services:
  avito-agent:
    build: .
    container_name: avito-agent
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
      - SELENIUM_HUB_HOST=selenium-hub
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_started
    networks:
      - avito-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  avito-mcp:
    build:
      context: ./Avito_autoload
      dockerfile: mcp_service/Dockerfile
    container_name: avito-mcp
    ports:
      - "8080:8080"
    volumes:
      - ./Avito_autoload/logs:/app/logs
      - ./Avito_autoload/out_xml:/app/out_xml
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - avito-net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  selenium-hub:
    image: seleniarm/hub:4.16.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - avito-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  chrome:
    image: seleniarm/node-chromium:4.16.1
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - avito-net

networks:
  avito-net:
    driver: bridge 