name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        AVITO_LOGIN: ${{ secrets.AVITO_LOGIN }}
        AVITO_PASSWORD: ${{ secrets.AVITO_PASSWORD }}
      run: |
        docker-compose up -d
        sleep 30  # Ждем инициализации контейнеров
        python -m pytest -v
        docker-compose down
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/avito
          git pull origin main
          echo "AVITO_LOGIN=${{ secrets.AVITO_LOGIN }}" > .env
          echo "AVITO_PASSWORD=${{ secrets.AVITO_PASSWORD }}" >> .env
          docker-compose down
          docker-compose build
          docker-compose up -d 